# Stage 1: Build GROMACS from Git repository
FROM ubuntu:24.04 as gromacs_builder

# Install dependencies for GROMACS
RUN apt-get update && \
    apt-get install -y \
    git \
    cmake \
    gcc \
    g++ \
    libfftw3-dev \
    libopenmpi-dev \
    libxml2-dev \
    liblapack-dev \
    libblas-dev \
    && rm -rf /var/lib/apt/lists/*

# Clone GROMACS repository (this layer will be cached unless the repo changes)
RUN git clone -b devel https://github.com/rrandiak/gromacs.git /gromacs

# Build GROMACS (this layer will be cached unless the source code changes)
WORKDIR /gromacs
RUN mkdir build
WORKDIR /gromacs/build
RUN cmake .. -DCMAKE_INSTALL_PREFIX=/opt/gromacs -DGMX_BUILD_OWN_FFTW=ON -DGMX_MPI=OFF -DGMX_GPU=OFF
RUN make -j$(nproc)
RUN make install

# Dockerfile.worker
FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y \
    libfftw3-dev \
    libxml2-dev \
    liblapack-dev \
    libblas-dev \
    python3 \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

    
WORKDIR /app

COPY . .

RUN python3 -m venv /opt/venv \
    && /opt/venv/bin/pip install --upgrade pip setuptools wheel \
    && /opt/venv/bin/pip install --no-cache-dir -r ./api/requirements.txt -r ./cli/requirements.txt

COPY --from=gromacs_builder /opt/gromacs /opt/gromacs

ENV PATH="/opt/gromacs/bin:/opt/venv/bin:${PATH}"
ENV LD_LIBRARY_PATH="/opt/gromacs/lib:${LD_LIBRARY_PATH}"

RUN ln -s ./cli/gmxextract.py /app/gmxextract.py && chmod +x /opt/gromacs/bin/gmx && chown -R 1000:1000 /app /opt/gromacs /opt/venv

USER 1000

# Entrypoint: start Celery worker
CMD ["celery", "-A", "api.app.celery", "worker", "--loglevel=debug", "--concurrency=4"]